name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v3.2.0
        with:
          client-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}
          release-type: dart

      - name: Assign PR to actor
        if: ${{ steps.release.outputs.pr != '' }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh pr edit ${{ fromJson(steps.release.outputs.pr).number }} --repo ${{ github.repository }} --add-assignee ${{ github.actor }} --add-reviewer konogannn
